server:
  port: 8036

spring:
  application:
    name: customer
  datasource:
    username: root
    url: jdbc:mysql://mysql:3306/microservice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: root123
  config:
    import: optional:configserver:http://config-server:8888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  boot:
    admin:
      client:
        url: http://admin-server:9090
  cloud:
    discovery:
      enabled: true
  main:
    web-application-type: reactive


management:
  endpoints:
    web:
      exposure:
        include: "*"
