server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/microservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  config:
    import: optional:configserver:http://config-server:8888
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
  cloud:
    discovery:
      enabled: true
  boot:
    admin:
      client:
        url: http://admin-server:9090


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

logging:
  level:
    org:
      hibernate: INFO
      springframework: INFO
    root: INFO
