server:
  port: 8038

spring:
  application:
    name: product
  datasource:
    username: root
    url: jdbc:mysql://mysql:3306/microservice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: ""
   config:
    import: optional:configserver:http://config-server:8888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  boot:
    admin:
      client:
        url: http://admin-server:9090
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
